# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a611ae47f7d345610aad70fcb13adccf93607922c00d5c8c750c8157622ca5310f17e56cbd2028e1c083783bbfe78ebddddcf04384735173a6f036d19a29da6c

test:
  secret_key_base: e4987a2d4a75e44ca66e088b4fd68e99cf908f8e69f2b6e6ed2876990e30c939c2426ff95bc8a173fc24f7eaf8000e22b84f37148e3863796067546d788b0deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
